# Generated by Django 4.2.7 on 2025-11-09 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='영상 ID')),
                ('title', models.CharField(help_text='사용자가 입력한 영상 제목 또는 파일명', max_length=255, verbose_name='영상 제목')),
                ('original_filename', models.CharField(help_text='업로드된 파일의 원래 이름', max_length=255, verbose_name='원본 파일명')),
                ('original_file_url', models.URLField(help_text='S3 또는 로컬 저장소의 원본 영상 경로', max_length=500, verbose_name='원본 파일 URL')),
                ('processed_file_url', models.URLField(blank=True, help_text='블러 처리가 완료된 영상 경로', max_length=500, null=True, verbose_name='처리된 파일 URL')),
                ('duration', models.FloatField(help_text='영상 전체 재생 시간', verbose_name='영상 길이 (초)')),
                ('width', models.IntegerField(help_text='영상 가로 픽셀 수 (예: 1920)', verbose_name='가로 해상도')),
                ('height', models.IntegerField(help_text='영상 세로 픽셀 수 (예: 1080)', verbose_name='세로 해상도')),
                ('fps', models.FloatField(help_text='초당 프레임 수 (예: 30.0, 60.0)', verbose_name='프레임 레이트')),
                ('file_size', models.BigIntegerField(help_text='원본 파일 크기 (바이트 단위)', verbose_name='파일 크기 (bytes)')),
                ('status', models.CharField(choices=[('uploaded', '업로드 완료'), ('analyzing', '얼굴 분석 중'), ('ready', '처리 대기'), ('processing', '영상 처리 중'), ('completed', '처리 완료'), ('failed', '실패')], db_index=True, default='uploaded', max_length=20, verbose_name='처리 상태')),
                ('progress', models.IntegerField(default=0, help_text='현재 작업 진행률 (0-100)', verbose_name='처리 진행률 (%)')),
                ('error_message', models.TextField(blank=True, help_text='처리 실패 시 에러 내용', null=True, verbose_name='에러 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='업로드 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('completed_at', models.DateTimeField(blank=True, help_text='영상 처리가 완료된 시각', null=True, verbose_name='처리 완료 일시')),
                ('expires_at', models.DateTimeField(blank=True, help_text='이 날짜 이후 파일 자동 삭제 (7일)', null=True, verbose_name='파일 만료 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='업로드 사용자')),
            ],
            options={
                'verbose_name': '영상',
                'verbose_name_plural': '영상 목록',
                'db_table': 'videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='작업 ID')),
                ('job_type', models.CharField(choices=[('face_analysis', '얼굴 분석'), ('video_processing', '영상 처리')], max_length=50, verbose_name='작업 종류')),
                ('celery_task_id', models.CharField(help_text='Celery에서 생성한 고유 작업 ID', max_length=255, unique=True, verbose_name='Celery 작업 ID')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('started', '실행 중'), ('success', '성공'), ('failure', '실패'), ('retry', '재시도 중'), ('revoked', '취소됨')], db_index=True, default='pending', max_length=20, verbose_name='작업 상태')),
                ('progress', models.IntegerField(default=0, verbose_name='진행률 (%)')),
                ('result_data', models.JSONField(blank=True, help_text='작업 완료 후 결과 정보 (JSON)', null=True, verbose_name='결과 데이터')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='에러 메시지')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작 일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 일시')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='videos.video', verbose_name='영상')),
            ],
            options={
                'verbose_name': '처리 작업',
                'verbose_name_plural': '처리 작업 목록',
                'db_table': 'processing_jobs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='얼굴 ID')),
                ('face_index', models.IntegerField(help_text='영상 내에서 발견된 순서 (1, 2, 3, ...)', verbose_name='얼굴 순번')),
                ('thumbnail_url', models.URLField(help_text='대표 얼굴 이미지 경로', max_length=500, verbose_name='썸네일 URL')),
                ('embedding', models.JSONField(help_text='FaceNet 512차원 특징 벡터 (JSON 배열)', verbose_name='임베딩 벡터')),
                ('appearance_count', models.IntegerField(default=0, help_text='영상 내 이 얼굴이 등장한 총 횟수', verbose_name='등장 횟수')),
                ('first_frame', models.IntegerField(help_text='이 얼굴이 처음 등장한 프레임 번호', verbose_name='첫 등장 프레임')),
                ('last_frame', models.IntegerField(help_text='이 얼굴이 마지막으로 등장한 프레임 번호', verbose_name='마지막 등장 프레임')),
                ('is_blurred', models.BooleanField(default=True, help_text='True면 블러 처리, False면 원본 유지', verbose_name='블러 처리 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='videos.video', verbose_name='영상')),
            ],
            options={
                'verbose_name': '얼굴',
                'verbose_name_plural': '얼굴 목록',
                'db_table': 'faces',
                'ordering': ['face_index'],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['user', '-created_at'], name='videos_user_id_5f9058_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status'], name='videos_status_510af8_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['video', '-started_at'], name='processing__video_i_681e46_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['celery_task_id'], name='processing__celery__4245d2_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['status'], name='processing__status_96bb49_idx'),
        ),
        migrations.AddIndex(
            model_name='face',
            index=models.Index(fields=['video', 'face_index'], name='faces_video_i_b06140_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='face',
            unique_together={('video', 'face_index')},
        ),
    ]
