# Generated by Django 4.2.7 on 2025-11-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='embeddings',
            field=models.JSONField(default=list, help_text='상위 3개 얼굴의 임베딩 벡터 리스트', verbose_name='다중 임베딩 벡터'),
        ),
    ]
