# Generated by Django 4.2.7 on 2025-12-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_instance_based_face_system'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='face',
            name='faces_video_i_b06140_idx',
        ),
        migrations.RenameIndex(
            model_name='face',
            new_name='faces_video_i_c14a33_idx',
            old_name='faces_video_instance_idx',
        ),
        migrations.RenameIndex(
            model_name='face',
            new_name='faces_quality_410efb_idx',
            old_name='faces_quality_idx',
        ),
        migrations.AlterField(
            model_name='face',
            name='embedding',
            field=models.JSONField(help_text='AdaFace 512차원 특징 벡터 (최고 품질, JSON 배열)', verbose_name='임베딩 벡터'),
        ),
        migrations.AlterField(
            model_name='face',
            name='thumbnail_url',
            field=models.URLField(help_text='최고 품질 얼굴 이미지 경로', max_length=500, verbose_name='썸네일 URL'),
        ),
    ]
