# Generated by Django 4.2.7 on 2025-12-04 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_face_faces_video_i_b06140_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='frame_data',
            field=models.JSONField(blank=True, default=dict, help_text='각 프레임에서의 bbox 위치 (JSON 객체)', verbose_name='프레임별 Tracking 데이터'),
        ),
    ]
